### PR TITLE
added -E flag to pass through all environment variables

### PR DESCRIPTION
**Pull request by bdupras**
@discordianfish any thoughts on implementing this feature per the comment by @dougborg in #1?

### CODE REVIEW

**Comment by discordianfish** [comment]
Totally reasonable, thanks for the PR!

**Comment by bdupras** [comment]
Awesome, thanks! When do you think you'll you cut the next release?

**Comment by discordianfish** [comment]
@bdupras [x] done

**Comment by bdupras** [comment]
:+1: @discordianfish

**Pull request merged**
